<!-- Code generated by gomarkdoc. DO NOT EDIT -->

# errgroup

```go
import "git.dev.cloud.mts.ru/billing/common/pkg/infra/errgroup"
```

## Index

- [type Group](<#type-group>)
  - [func New() *Group](<#func-new>)
  - [func WithCancelOnErr(ctx context.Context) *Group](<#func-withcancelonerr>)
  - [func (g *Group) Context() context.Context](<#func-group-context>)
  - [func (g *Group) Go(f func() error)](<#func-group-go>)
  - [func (g *Group) Wait() error](<#func-group-wait>)
  - [func (g *Group) WithMaxConcurrency(factor int) *Group](<#func-group-withmaxconcurrency>)


## type [Group](<https://git.dev.cloud.mts.ru/billing/common/blob/master/pkg/infra/errgroup/errgroup.go#L13-L20>)

Group \- набор горутин для запуска подзадач некоторой большой задачи с возможностью обработки ошибок каждой из подзадач и возврата наверх их списка в виде \`errors\.Chain\`

```go
type Group struct {
    // contains filtered or unexported fields
}
```

### func [New](<https://git.dev.cloud.mts.ru/billing/common/blob/master/pkg/infra/errgroup/errgroup.go#L24>)

```go
func New() *Group
```

New \- конструктор пустой группы\, юзкейс когда отрабатывают все подзадачи\, невзирая на ошибки в некоторых из них или во всех

### func [WithCancelOnErr](<https://git.dev.cloud.mts.ru/billing/common/blob/master/pkg/infra/errgroup/errgroup.go#L30>)

```go
func WithCancelOnErr(ctx context.Context) *Group
```

WithCancelOnErr \- конструктор группы с унаследованным контекстом\, юзкейс в котором при возникновении первой ошибки в одной из подзадач \- выполнение всех подзадач прерывается

### func \(\*Group\) [Context](<https://git.dev.cloud.mts.ru/billing/common/blob/master/pkg/infra/errgroup/errgroup.go#L48>)

```go
func (g *Group) Context() context.Context
```

Context \- возвращает родительский контекст\.

### func \(\*Group\) [Go](<https://git.dev.cloud.mts.ru/billing/common/blob/master/pkg/infra/errgroup/errgroup.go#L66>)

```go
func (g *Group) Go(f func() error)
```

Go \- запуск выполнения подзадачи в группу

### func \(\*Group\) [Wait](<https://git.dev.cloud.mts.ru/billing/common/blob/master/pkg/infra/errgroup/errgroup.go#L55>)

```go
func (g *Group) Wait() error
```

Wait \- ожидание завершения работы подзадач\. Возвращает первую ошибку в случае использования кейса прерывания по ошибке и набор ошибок объединенных в \`errors\.Chain\` с помощью And в случае кейса непрерывной работы

### func \(\*Group\) [WithMaxConcurrency](<https://git.dev.cloud.mts.ru/billing/common/blob/master/pkg/infra/errgroup/errgroup.go#L41>)

```go
func (g *Group) WithMaxConcurrency(factor int) *Group
```

WithMaxConcurrency \- устанавливает максимальное количество выполняемых одновременно подзадач



